name: aws-github-runner-action
description: GitHub Action for automatic EC2 instance creation and registering it as a self-hosted GitHub Actions runner
author: Volodymyr Machula
inputs:
  github_token:
    description: GitHub Secret Token with a 'repo' scope assigned
    required: true
  ec2_image_id:
    description: '' # TODO, possible values: start, stop
    required: true
  ec2_instance_type:
    description: '' # TODO, possible values: start, stop
    required: true
  subnet_id:
    description: '' # TODO, possible values: start, stop
    required: true
  security_group_id:
    description: '' # TODO, possible values: start, stop
    required: true
  label:
    description: '' # TODO, possible values: start, stop
    required: false
outputs:
  label:
    description: '' # TODO
runs:
  using: node12
  main: ./dist/index.js
  post: ./dist/cleanup/index.js
